# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - Rscript install_inzight.R
  - appveyor DownloadFile "http://ftp.gnome.org/pub/gnome/binaries/win32/gtk+/2.22/gtk+-bundle_2.22.1-20101227_win32.zip" -FileName gtk32.zip
  - md gtk
  - cd gtk
  - md i386
  - cd i386
  - 7z x ..\..\gtk32.zip > nul
  - cd ..
  - cd ..
  - if exist c:\RLibrary\RGtk2\gtk\ rd /s /q c:\RLibrary\RGtk2\gtk
  - mv gtk c:\RLibrary\RGtk2
  - del gtk32.zip

environment:
  R_VERSION: release
#  USE_RTOOLS: true
#  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

# Adapt as necessary starting from here

build_script:
  - mv C:\R R
  - mv C:\RLibrary library
  - Rscript rgui_settings.R
  - makensis.exe inzight_installer.nsi

#test_script:
#  - md C:\Users\appveyor\Documents\iNZightVIT
#  - travis-tool.sh run_tests

#on_success:
  
on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

  - path: '\*.exe'
    name: Installer
